services:
  bot:
    build:
      context: ./backend/bot
      dockerfile: Dockerfile.bot.prod
    container_name: bot
    depends_on:
      - mongodb
      - server

  server:
    build:
      context: ./backend/server
      dockerfile: Dockerfile.server.prod
    container_name: server
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: zadvizh
      MONGO_INITDB_ROOT_PASSWORD: wwGDSqseqDFFBDSS

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: admins
      ME_CONFIG_MONGODB_ADMINUSERNAME: zadvizh
      ME_CONFIG_MONGODB_ADMINPASSWORD: wwGDSqseqDFFBDSS
      ME_CONFIG_MONGODB_URL: mongodb://zadvizh:wwGDSqseqDFFBDSS@mongodb:27017/zadvizh?ssl=false&authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: jjHV3XaqlqaE74a7T70F
    depends_on:
      - server
      - mongodb