services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.bot.dev
    container_name: bot
    volumes:
      - ./bot:/app
    depends_on:
      - mongodb
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    depends_on:
      - server
      - mongodb