FROM golang:1.23-alpine AS builder

ENV SERVER_PORT=5000
ENV MONGO_URI=mongodb://admin:admin@mongodb:27017/zadvizh?ssl=false&authSource=admin
ENV MONGODB=zadvizh
ENV JWT_SECRET_KEY=IimULHg9FRS0XleGnPZo

WORKDIR /build

COPY go.* .

RUN go mod download && \
    go mod verify && \
    go mod tidy

COPY . .

RUN go build -ldflags="-s -w" -o /build/main ./cmd/main.go

FROM alpine AS prod

WORKDIR /app

COPY --from=builder /build/main /app/main

CMD ["/app/main"]