FROM golang:1.23-alpine AS builder

ENV SERVER_PORT=5000
ENV MONGO_URI=mongodb://admin:admin@mongodb:27017/
ENV MONGO_APP_NAME=zadvizh

WORKDIR /app

COPY . .

RUN go mod download

RUN go install github.com/air-verse/air@latest

CMD ["air","-c",".air.toml"]