FROM golang:1.23-alpine AS builder

ENV BOT_TOKEN=7950443390:AAFaHXb6prhYCBFXpiLEXdKAav9dz4GrGrk
ENV LINK_TEMPLATE=http://localhost:5000/?ref=Z@6v1ZH_invite_link_

WORKDIR /app

COPY . .

RUN go mod download

RUN go install github.com/air-verse/air@latest

CMD ["air","-c",".air.toml"]